// Edit this file to configure your possible headers for the start page
window.BROTON_HEADERS = [
  "Sup, Bitch?",
  "Now what?",
  "Here we go again...",
  "We breakin' shit?",
  "Remember when Grok became MechaHitler?",
  "Fuck, I stubbed my toe...",
  "Yippee-ki-yay, motherfucker.",
  "I’ll be back.",
  "Say hello to my little friend!",
  "I’m all outta gum.",
  "There's no way that EVERYBODY was kung fu fighting.",
  "You're locked in here with ME.",
  "Dodge this.",
  "Get to the chopper!",
  "You can’t handle the truth!",
  "I'm your huckleberry.",
  "Why so serious?",
  "Tis but a scratch",
  "I am the law!",
  "Han shot first.",
  "Where we’re going, we don’t need roads.",
  "Hasta la vista, baby.",
  "I am inevitable.",
  "Kneel before Zod.",
  "Meat’s back on the menu, boys!",
  "You’re gonna need a bigger boat.",
  "I see dead people.",
  "Snakes. Why’d it have to be snakes?",
  "I’m too old for this shit.",
  "You picked the wrong house, fool!",
  "Do a barrel roll!",
  "War. War never changes.",
  "Rip and tear, until it is done.",
  "YOU DIED.",
  "You are unconscious.",
  "Prepare to die.",
  "Praise the sun!",
  "Blood for the blood god!",
  "Skulls for the skull throne!",
  "Nothing personnel... kid.",
  "Just ask Chad Jippity",
  "You have dysentery.",
  "You have died of dysentery.",
  "You bring dishonor to your family.",
  "dQw4w9WgXcQ",
  "Prepare for unforeseen consequences.",
  "War's over, son.",
  "Don't drink the water.",
  "I don't even remember why I came here.",
  "It's time to choose.",
  "Would you kindly...",
  "A man chooses, a slave obeys.",
  "No gods or kings, only man.",
  "We all make choices.",
  "I am Andrew Ryan.",
  "THE NUMBERS MASON, WHAT DO THEY MEAN?",
  "Death and taxes.",
  "LITERALLY FUCK YOUR OWN FACE!",
  "No Russian.",
  "There is no header.",
  "No gods or kings, only man.",
  "What kinda punk-ass pills are these?",
  "Wait, no. You can't search for that.",
  "MDE never dies.",
  "You ever listen to buttrock?",
  "BAKUSHIN!",
  "Give your balls a tug."
];